services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: toor-frontend:latest
    container_name: toor-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: toor-backend:latest
    container_name: toor-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/toor
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: toor-mongodb
    environment:
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: