require("dotenv").config();
const express=require("express"), cors=require("cors"), connectDatabase=require("./config/database");
const app=express();
app.use(cors());app.use(express.json());
app.get("/api/health",(req,res)=>res.json({status:"ok",service:"toor-backend"}));
app.use("/api/products",require("./routes/products"));
app.use("/api/categories",require("./routes/categories"));
app.use("/api/orders",require("./routes/orders"));
app.use("/api/users",require("./routes/users"));
app.use("/api/contact",require("./routes/contact"));
const PORT=process.env.PORT||5000;
connectDatabase().then(()=>app.listen(PORT,()=>console.log(`Toor API running on port ${PORT}`))).catch(err=>{console.error("Database connection failed:",err.message);process.exit(1);});
